# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libsndfile1 \
    ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Copy source
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir .

# Default command to run the MCP server
CMD ["mcp-music-analysis"]
