# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Install system dependencies for audio processing
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libsndfile1 \
    ffmpeg \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml requirements-dev.txt .
COPY src ./src
COPY public ./public
COPY chroma.csv ./
COPY test.py ./
COPY uv.lock ./

# Install Python dependencies and the MCP server
RUN pip install --no-cache-dir pip setuptools wheel \
 && pip install --no-cache-dir .

# Default command to run the MCP server
CMD ["mcp-music-analysis"]
